config/routes.rb
Rails.application.routes.draw do

  root to: 'games#index'

  get 'games', to: 'games#index'
  get 'games/game_session', to: 'games#game_session'
  get 'games/game_session_questions/:id', to: 'games#game_session_questions'
  get 'games/collegiate_rivals', to: 'games#collegiate_rivals'

  get 'profiles', to: 'profiles#show'
  get 'profiles/:id', to: 'profiles#show'
  get 'profiles/:id/edit', to: 'profiles#edit'

  get 'schools/teachers', to: 'schools#teachers'
  get 'schools/students', to: 'schools#students'
  get 'schools/new_user', to: 'schools#new_user', as: 'school_new_user'
  get 'schools/edit_user/:id', to: 'schools#edit_user', as: 'school_edit_user'
  post 'schools/new_user', to: 'schools#create_new_user'
  patch 'schools/edit_user/:id', to: 'schools#update_user', as: 'school_update_user'
  delete 'schools/new_user/:id', to: 'schools#delete_user', as: 'school_delete_user'

  get 'questions/classroom/:id', to: 'questions#classroom', as: 'classroom_questions'
  get 'questions/classroom/:id/new', to: 'questions#new', as: 'new_classroom_question'
  post 'questions/classroom/:classroom_id', to: 'questions#create', as: 'create_new_classroom_question'

  get 'classroom_users/classroom/:id', to: 'classroom_users#index', as: 'classroom_users_class'
  post 'classroom_users/classroom/:id', to: 'classroom_users#create', as: 'classroom_users_add'

  post 'rewards/send_email', to: 'rewards#send_email'

  devise_for :users, controllers: {
      sessions: 'users/sessions'
  }
  resources :schools
  resources :classrooms
  resources :questions
  resources :classroom_users
end

app/models/classroom.rb
class Classroom < ActiveRecord::Base

  belongs_to :school
  has_many :questions
  has_many :classroom_users

  has_many :users, :through => :classroom_users

  validates :name, :subject, :user_id, presence: true

end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
  before_action :set_classroom, only: [:show, :edit, :update, :destroy]
  before_action :set_user

  # GET /classrooms
  # GET /classrooms.json
  def index
    if @user.role == 1
      @classrooms = Classroom.where(user_id: @user.id)
    elsif @user.role == 2
      @classrooms = Classroom.where(school_id: @user.school_id)
      @teachers = []

      @classrooms.each do |classroom|
        teacher = User.find(classroom.user_id)
        @teachers.push(teacher)
      end
    else
      redirect_to root_path
    end
  end

  # GET /classrooms/1
  # GET /classrooms/1.json
  def show
  end

  # GET /classrooms/new
  def new
    @classroom = Classroom.new
  end

  # GET /classrooms/1/edit
  def edit
  end

  # POST /classrooms
  # POST /classrooms.json
  def create
    @classroom = Classroom.new(classroom_params)
    @classroom.school_id = @user.school_id

    respond_to do |format|
      if @classroom.save
        format.html { redirect_to classrooms_path, notice: 'Classroom was successfully created.' }
        format.json { render :show, status: :created, location: @classroom }
      else
        format.html { render :new }
        format.json { render json: @classroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /classrooms/1
  # PATCH/PUT /classrooms/1.json
  def update
    respond_to do |format|
      if @classroom.update(classroom_params)
        format.html { redirect_to classrooms_url, notice: 'Classroom was successfully updated.' }
        format.json { render :show, status: :ok, location: @classroom }
      else
        format.html { render :edit }
        format.json { render json: @classroom.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classrooms/1
  # DELETE /classrooms/1.json
  def destroy
    @classroom.classroom_users.destroy_all
    @classroom.destroy
    respond_to do |format|
      format.html { redirect_to classrooms_url, notice: 'Classroom was successfully deleted.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_classroom
      @classroom = Classroom.find(params[:id])
    end

    def set_user
      id = current_user.id
      @user = User.find(id)
      @teachers = User.where(school_id: @user.school_id, role: 1)

      unless @user.role > 0
        redirect_to root_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def classroom_params
      params.require(:classroom).permit(:name, :subject, :school_id, :user_id)
    end
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/views/classrooms/_form.html.erb
<%= form_for(@classroom) do |f| %>
  <% if @classroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@classroom.errors.count, "error") %> prohibited this classroom from being saved:</h2>

      <ul>
      <% @classroom.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


    <div class="row">
      <div class="col-sm-4">
        <fieldset class="form-group">
          <%= f.label :name %><br>
          <%= f.text_field :name, class: 'form-control' %>
        </fieldset>
      </div>

      <div class="col-sm-4">
        <fieldset class="form-group">
          <%= f.label :subject %><br>
          <%= f.text_field :subject, class: 'form-control' %>
        </fieldset>
      </div>

      <div class="col-sm-4">
        <fieldset class="form-group">
          <%= f.label 'Teacher' %><br>
          <select name="classroom[user_id]" id="classroom_user_id" class="form-control">
            <% @teachers.each do |t| %>
                <% if @classroom.user_id == t.id %>
                    <option value="<%= t.id %>" selected><%= t.first_name %> <%= t.last_name %></option>
                <% else %>
                    <%= content_tag(:option, t.first_name + ' ' + t.last_name, value: t.id) %>
                <% end %>
            <% end %>
          </select>
        </fieldset>
      </div>
    </div>

    <p>&nbsp;</p>

    <div class="actions">
      <%= f.submit class: 'btn btn-primary' %>
    </div>

    <%= link_to 'Cancel', classrooms_path, class: 'chalk_link' %>
<% end %>

app/views/classrooms/edit.html.erb
<%= render 'layouts/header_main' %>

<div class="content_overlay content_column">
  <div class="container-fluid content_overlay">

    <h1>Edit <%= @classroom.name %></h1>

    <%= render 'form' %>

  </div>
</div>

app/views/classrooms/index.html.erb
<%= render 'layouts/header_main' %>

<div class="content_overlay content_column">
  <div class="container-fluid content_overlay">
    <p id="notice"><%= notice %></p>

    <h1>Classrooms</h1>

    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Subject</th>
          <% if @user.role == 2 %>
              <th>Teacher</th>
          <% end %>
          <th>Classroom Options</th>
          <% if @user.role == 2 %>
            <th>Admin Options</th>
          <% end %>
        </tr>
      </thead>

      <tbody>
        <% i = -1 %>
        <% @classrooms.each do |classroom| %>
          <% i += 1 %>
          <tr>
            <td><%= classroom.name %></td>
            <td><%= classroom.subject %></td>
            <% if @user.role == 2 %>
              <td><%= @teachers[i].first_name %> <%= @teachers[i].last_name %></td>
            <% end %>
            <td><p><%= link_to 'Students', classroom_users_class_path(classroom.id), class: 'btn btn-success' %></p>
              <p><%= link_to 'Questions', classroom_questions_path(classroom), class: 'btn btn-success' %></p></td>

            <% if @user.role == 2 %>
              <td><p><%= link_to 'Edit', edit_classroom_path(classroom), class: 'btn btn-warning' %></p>
                <p><%= link_to 'Delete', classroom, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></p></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>

    <br>

    <% if @user.role == 2 %>
      <%= link_to 'New Classroom', new_classroom_path, class: 'btn btn-primary' %>
    <% end %>
  </div>
</div>

app/views/classrooms/new.html.erb
<%= render 'layouts/header_main' %>

<div class="content_overlay content_column">
  <div class="container-fluid content_overlay">

    <h1>New Classroom</h1>

    <%= render 'form' %>

  </div>
</div>

app/views/classrooms/show.html.erb
<%= render 'layouts/header_main' %>

<div class="content_overlay content_column">
  <div class="container-fluid content_overlay">

    <h1><%= @classroom.name %></h1>

    <p id="notice"><%= notice %></p>

    <table class="table">
      <thead>
      <tr>
        <th>Name</th>
        <th>Email</th>
        <th>Admin Options</th>
      </tr>
      </thead>

      <tbody>
      <tr>
        <td>Student Name</td>
        <td>student@email.com</td>
        <td><%= link_to 'Remove', '#', class: 'btn btn-danger', data: { confirm: 'Are you sure?' } %></td>
      </tr>
      </tbody>
    </table>

    <p><%= link_to 'Add Student', '#', class: 'btn btn-primary' %></p>
    <p><%= link_to 'Back', classrooms_path, class: 'btn btn-danger' %></p>
  </div>
</div>