config/routes.rb
Rails.application.routes.draw do

  root to: 'games#index'

  get 'games', to: 'games#index'
  get 'games/game_session', to: 'games#game_session'
  get 'games/game_session_questions/:id', to: 'games#game_session_questions'
  get 'games/collegiate_rivals', to: 'games#collegiate_rivals'

  get 'profiles', to: 'profiles#show'
  get 'profiles/:id', to: 'profiles#show'
  get 'profiles/:id/edit', to: 'profiles#edit'

  get 'schools/teachers', to: 'schools#teachers'
  get 'schools/students', to: 'schools#students'
  get 'schools/new_user', to: 'schools#new_user', as: 'school_new_user'
  get 'schools/edit_user/:id', to: 'schools#edit_user', as: 'school_edit_user'
  post 'schools/new_user', to: 'schools#create_new_user'
  patch 'schools/edit_user/:id', to: 'schools#update_user', as: 'school_update_user'
  delete 'schools/new_user/:id', to: 'schools#delete_user', as: 'school_delete_user'

  get 'questions/classroom/:id', to: 'questions#classroom', as: 'classroom_questions'
  get 'questions/classroom/:id/new', to: 'questions#new', as: 'new_classroom_question'
  post 'questions/classroom/:classroom_id', to: 'questions#create', as: 'create_new_classroom_question'

  get 'classroom_users/classroom/:id', to: 'classroom_users#index', as: 'classroom_users_class'
  post 'classroom_users/classroom/:id', to: 'classroom_users#create', as: 'classroom_users_add'

  post 'rewards/send_email', to: 'rewards#send_email'

  devise_for :users, controllers: {
      sessions: 'users/sessions'
  }
  resources :schools
  resources :classrooms
  resources :questions
  resources :classroom_users
end

app/models/classroom_user.rb
class ClassroomUser < ActiveRecord::Base
  belongs_to :user
  belongs_to :classroom

  validates :user_id, :classroom_id, presence: true
  validates :user_id, uniqueness: { scope: :classroom_id }

end

app/controllers/classroom_users_controller.rb
class ClassroomUsersController < ApplicationController
  before_action :set_classroom_user, only: [:show, :edit, :update, :destroy]
  before_action :get_students, only: [:index]
  before_action :set_classroom, only: [:index]
  before_action :get_all_students, only: [:index]

  # GET /classroom_users
  # GET /classroom_users.json
  def index
  end

  # GET /classroom_users/1
  # GET /classroom_users/1.json
  def show
  end

  # GET /classroom_users/new
  def new
    @classroom_user = ClassroomUser.new
  end

  # GET /classroom_users/1/edit
  def edit
  end

  # POST /classroom_users
  # POST /classroom_users.json
  def create
    @classroom_user = ClassroomUser.new(classroom_user_params)

    respond_to do |format|
      if @classroom_user.save
        format.html { redirect_to classroom_users_class_path(classroom_user_params[:classroom_id]), notice: 'Student was successfully added to class.' }
        format.json { render :show, status: :created, location: @classroom_user }
      else
        # format.html { render :new }
        format.html { redirect_to classroom_users_class_path(classroom_user_params[:classroom_id]), notice: 'Student is already in this class'}
        format.json { render json: @classroom_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /classroom_users/1
  # PATCH/PUT /classroom_users/1.json
  def update
    respond_to do |format|
      if @classroom_user.update(classroom_user_params)
        format.html { redirect_to @classroom_user, notice: 'Student was successfully added to class.' }
        format.json { render :show, status: :ok, location: @classroom_user }
      else
        format.html { render :edit }
        format.json { render json: @classroom_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classroom_users/1
  # DELETE /classroom_users/1.json
  def destroy
    @classroom_user.destroy
    respond_to do |format|
      format.html { redirect_to classroom_users_class_path(@classroom_user.classroom_id), notice: 'Student was successfully removed from class.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_classroom_user
      @classroom_user = ClassroomUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def classroom_user_params
      params.require(:classroom_users).permit(:classroom_id, :user_id)
    end

    def get_students
      @classroom_users = ClassroomUser.where(classroom_id: params[:id])

      @students = []

      @classroom_users.each do |user|
        student = User.find(user.user_id)
        student.classroom_id = user.id
        @students.push student
      end
    end

    def set_classroom
      @classroom = Classroom.find(params[:id])
    end

    def get_all_students
      user = User.find(current_user.id)
      id = user.school_id
      @all_students = User.where(school_id: id, role: 0)
    end
end

app/helpers/classroom_users_helper.rb
module ClassroomUsersHelper
end

app/views/classroom_users/_form.html.erb
<%= form_for(@classroom_user) do |f| %>
  <% if @classroom_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@classroom_user.errors.count, "error") %> prohibited this classroom_user from being saved:</h2>

      <ul>
      <% @classroom_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/classroom_users/edit.html.erb
<h1>Editing Classroom User</h1>

<%= render 'form' %>

<%= link_to 'Show', @classroom_user %> |
<%= link_to 'Back', classroom_users_path %>

app/views/classroom_users/index.html.erb
<%= render 'layouts/header_main' %>

<div class="content_overlay content_column">
  <div class="container-fluid content_overlay">

    <p id="notice"><%= notice %></p>

    <h1><%= @classroom.name %></h1>

    <table class="table">
      <thead>
        <tr>
          <th>Student</th>
          <th>Email</th>
          <th>Admin Options</th>
        </tr>
      </thead>

      <tbody>
      <% @students.each do |student| %>
          <tr>
            <td><%= student.first_name %> <%= student.last_name %></td>
            <td><%= student.email %></td>
            <td><a href="/classroom_users/<%= student.classroom_id %>" data-method="delete" data-confirm="Are you sure?" class="btn btn-danger">Remove</a></td>
          </tr>
      <% end %>
      </tbody>
    </table>

    <br>

    <div class="row">
      <div class="col-sm-6">
        <h2>Add Student</h2>

        <%= form_for :classroom_users, url: classroom_users_add_path(@classroom) do |f| %>
            <%= f.hidden_field :classroom_id, value: @classroom.id %>
            <fieldset class="form-group">
              <select name="classroom_users[user_id]" id="classroom_users_user_id" class="form-control">
                <% @all_students.each do |student| %>
                    <%= content_tag(:option, student.first_name + ' ' + student.last_name, value: student.id) %>
                <% end %>
              </select>
            </fieldset>

            <div class="actions">
              <%= f.submit 'Add to Class', class: 'btn btn-primary', data: { confirm: 'Are you sure?' } %>
            </div>
        <% end %>

        <%= link_to 'Classrooms', classrooms_path, class: 'chalk_link' %>
      </div>
    </div>

  </div>
</div>

app/views/classroom_users/new.html.erb
<h1>New Classroom User</h1>

<%= render 'form' %>

<%= link_to 'Back', classroom_users_path %>

app/views/classroom_users/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_classroom_user_path(@classroom_user) %> |
<%= link_to 'Back', classroom_users_path %>