config/routes.rb
Rails.application.routes.draw do

  root to: 'games#index'

  get 'games', to: 'games#index'
  get 'games/game_session', to: 'games#game_session'
  get 'games/game_session_questions/:id', to: 'games#game_session_questions'
  get 'games/collegiate_rivals', to: 'games#collegiate_rivals'

  get 'profiles', to: 'profiles#show'
  get 'profiles/:id', to: 'profiles#show'
  get 'profiles/:id/edit', to: 'profiles#edit'

  get 'schools/teachers', to: 'schools#teachers'
  get 'schools/students', to: 'schools#students'
  get 'schools/new_user', to: 'schools#new_user', as: 'school_new_user'
  get 'schools/edit_user/:id', to: 'schools#edit_user', as: 'school_edit_user'
  post 'schools/new_user', to: 'schools#create_new_user'
  patch 'schools/edit_user/:id', to: 'schools#update_user', as: 'school_update_user'
  delete 'schools/new_user/:id', to: 'schools#delete_user', as: 'school_delete_user'

  get 'questions/classroom/:id', to: 'questions#classroom', as: 'classroom_questions'
  get 'questions/classroom/:id/new', to: 'questions#new', as: 'new_classroom_question'
  post 'questions/classroom/:classroom_id', to: 'questions#create', as: 'create_new_classroom_question'

  get 'classroom_users/classroom/:id', to: 'classroom_users#index', as: 'classroom_users_class'
  post 'classroom_users/classroom/:id', to: 'classroom_users#create', as: 'classroom_users_add'

  post 'rewards/send_email', to: 'rewards#send_email'

  devise_for :users, controllers: {
      sessions: 'users/sessions'
  }
  resources :schools
  resources :classrooms
  resources :questions
  resources :classroom_users
end

app/models/school.rb
class School < ActiveRecord::Base
  has_many :users
  has_many :classrooms
  has_many :questions

  validates :name, :address, :city, :state, :zip, :mascot, presence: true
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  before_action :set_school, only: [:show, :edit, :update, :destroy]
  before_action :set_user, except: [:edit_user, :update_user]

  # GET /schools
  # GET /schools.json
  def index
    # @schools = School.all
    @schools = School.find_by(id: @user.school_id)
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
  end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1
  # PATCH/PUT /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to schools_path, notice: 'School was successfully updated.' }
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url, notice: 'School was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  #########
  # USERS - ACTIONS OUTSIDE OF DEVISE USER
  #########

  # GET ALL TEACHERS
  def teachers
    school = @user.school_id
    @teachers = User.where(school_id: school, role: 1)
  end

  # GET ALL STUDENTS
  def students
    school = @user.school_id
    @students = User.where(school_id: school, role: 0)
  end

  # GET NEW USER
  def new_user
    @new_user = User.new
  end

  # CREATE NEW USER
  def create_new_user
    @new_user = User.new(user_params)
    @new_user.school_id = @user.school_id

    respond_to do |format|
      if @new_user.save
        if @new_user.role == 1
          format.html { redirect_to schools_teachers_path, notice: 'Teacher was successfully created.' }
        else
          format.html { redirect_to schools_students_path, notice: 'Student was successfully created.' }
        end

        format.json { render :index, status: :created }
      else
        format.html { render :new_user }
        format.json { render json: @new_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # EDIT USER
  def edit_user
    @user = User.find(params[:id])
  end

  # UPDATE USER
  def update_user
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update(user_params)
        if @user.role == 1
          format.html { redirect_to schools_teachers_path, notice: 'Teacher was successfully updated.' }
          format.json { render json: @user, status: :ok }
        else
          format.html { redirect_to schools_students_path, notice: 'Student was successfully updated.' }
          format.json { render json: @user, status: :ok }
        end
      else
        format.html { render :edit_user }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE USER
  def delete_user
    @user = User.find(params[:id])
    @user.classroom_users.destroy_all
    @user.destroy
    respond_to do |format|
      if @user.role == 1
        format.html { redirect_to schools_teachers_path, notice: 'Teacher was successfully deleted.' }
        format.json { head :no_content }
      else
        format.html { redirect_to schools_students_path, notice: 'Student was successfully deleted.' }
        format.json { head :no_content }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_params
      params.require(:school).permit(:name, :address, :city, :state, :zip, :mascot)
    end

    # SET USER PARAMS
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :role, :game_wins, :game_losses)
    end

    # SET USER
    def set_user
      id = current_user.id
      @user = User.find(id)

      unless @user.role == 2
        redirect_to root_path
      end
    end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_form.html.erb
<%= form_for(@school) do |f| %>
  <% if @school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@school.errors.count, "error") %> prohibited this school from being saved:</h2>

      <ul>
      <% @school.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="col-sm-6">
      <fieldset class="form-group">
        <%= f.label :name %><br>
        <%= f.text_field :name, class: "form-control" %>
      </fieldset>
    </div>

    <div class="col-sm-6">
      <fieldset class="form-group">
        <%= f.label :mascot %><br>
        <%= f.text_field :mascot, class: "form-control" %>
      </fieldset>
    </div>
  </div>


    <div class="row">
      <div class="col-sm-12">
        <fieldset class="form-group">
          <%= f.label :address %><br>
          <%= f.text_field :address, class: "form-control" %>
        </fieldset>
      </div>
    </div>


    <div class="row">
      <div class="col-sm-4">
        <fieldset class="form-group">
          <%= f.label :city %><br>
          <%= f.text_field :city, class: "form-control" %>
        </fieldset>
      </div>

      <div class="col-sm-4">
        <fieldset class="form-group">
          <%= f.label :state %><br>
          <%= f.text_field :state, class: "form-control" %>
        </fieldset>
      </div>

      <div class="col-sm-4">
        <fieldset class="form-group">
          <%= f.label :zip %><br>
          <%= f.text_field :zip, class: "form-control" %>
        </fieldset>
      </div>
    </div>

    <p>&nbsp;</p>

    <div class="actions">
      <%= f.submit 'Update School', class: "btn btn-primary" %>
    </div>

    <%= link_to 'Cancel', schools_path, class: 'chalk_link' %>
<% end %>

app/views/schools/edit.html.erb
<%= render 'layouts/header_main' %>

<div class="content_overlay content_column">
  <div class="container-fluid content_overlay">

    <h1>Edit School</h1>

    <%= render 'form' %>

  </div>
</div>

app/views/schools/edit_user.html.erb
<%= render 'layouts/header_main' %>

<div class="content_overlay content_column">
  <div class="container-fluid content_overlay">

    <p id="notice"><%= notice %></p>

    <h1>Edit User</h1>

    <%= form_for(@user, url: school_update_user_path(@user)) do |f| %>

        <% if @user.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

              <ul>
                <% @user.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

      <div class="row">
        <div class="col-sm-6">
          <fieldset class="form-group">
            <%= f.label :first_name %><br />
            <%= f.text_field :first_name, class: 'form-control' %>
          </fieldset>
        </div>

        <div class="col-sm-6">
          <fieldset class="form-group">
            <%= f.label :last_name %><br />
            <%= f.text_field :last_name, class: 'form-control' %>
          </fieldset>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-6">
          <fieldset class="form-group">
            <%= f.label :email %><br />
            <%= f.email_field :email, class: 'form-control' %>
          </fieldset>
        </div>

        <div class="col-sm-6">
          <fieldset class="form-group">
            <%= f.label 'Permissions' %>
            <select name="user[role]" id="user_role" class="form-control">
              <option value="0">Student</option>
              <option value="1" <% if @user.role == 1 %> selected <% end %> >Teacher</option>
            </select>
          </fieldset>
        </div>
      </div>

        <p>&nbsp;</p>

        <div class="actions">
          <%= f.submit 'Update User', class: 'btn btn-primary' %>
        </div>
    <% end %>

    <%= link_to 'Cancel', schools_path, class: 'chalk_link' %>

  </div>
</div>

app/views/schools/index.html.erb
<%= render 'layouts/header_main' %>

<div class="content_overlay content_column">
  <div class="container-fluid content_overlay">
    <p id="notice"><%= notice %></p>

    <h1><%= @schools.name %></h1>

      <table class="table">
        <thead>
          <tr>
            <th>Address</th>
            <th>City</th>
            <th>State</th>
            <th>Zip</th>
            <th>Mascot</th>
          </tr>
        </thead>

        <tbody>
          <tr>
            <td><%= @schools.address %></td>
            <td><%= @schools.city %></td>
            <td><%= @schools.state %></td>
            <td><%= @schools.zip %></td>
            <td><%= @schools.mascot %></td>
          </tr>
        </tbody>
      </table>

    <p>&nbsp;</p>

    <p><%= link_to 'Edit School', edit_school_path(@schools), class: 'btn btn-primary' %></p>

    <p>&nbsp;</p>

    <div class="row">
      <div class="col-sm-6">
        <h2>Teachers</h2>
        <%= link_to 'View', schools_teachers_path, class: 'btn btn-success' %>
      </div>

      <div class="col-sm-6">
        <h2>Students</h2>
        <%= link_to 'View', schools_students_path, class: 'btn btn-success' %>
      </div>
    </div>

  </div>
</div>

app/views/schools/new.html.erb
<%= render 'layouts/header_main' %>

<div class="content_column content_overlay">
  <div class="container-fluid">

    <h1>New School</h1>

    <%= render 'form' %>

    <%= link_to 'Back', schools_path, class: "btn btn-danger" %>

  </div>
</div>

app/views/schools/new_user.html.erb
<%= render 'layouts/header_main' %>

<div class="content_overlay content_column">
  <div class="container-fluid content_overlay">

    <p id="notice"><%= notice %></p>

    <h1>Create New User</h1>

    <%= form_for(@new_user, url: '/schools/new_user') do |f| %>
        <% if @new_user.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@new_user.errors.count, "error") %> prohibited this user from being saved:</h2>

              <ul>
                <% @new_user.errors.full_messages.each do |message| %>
                    <li><%= message %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

      <div class="row">
        <div class="col-sm-6">
          <fieldset class="form-group">
            <%= f.label :first_name %><br />
            <%= f.text_field :first_name, class: 'form-control' %>
          </fieldset>
        </div>

        <div class="col-sm-6">
          <fieldset class="form-group">
            <%= f.label :last_name %><br />
            <%= f.text_field :last_name, class: 'form-control' %>
          </fieldset>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-6">
          <fieldset class="form-group">
            <%= f.label :email %><br />
            <%= f.email_field :email, class: 'form-control' %>
          </fieldset>
        </div>

        <div class="col-sm-6">
          <fieldset class="form-group">
            <%= f.label :role, 'Permissions' %>
            <select name="user[role]" id="user_role" class="form-control">
              <option value="0">Student</option>
              <option value="1">Teacher</option>
            </select>
          </fieldset>
        </div>
      </div>

      <div class="row">
        <div class="col-sm-6">
          <fieldset class="form-group">
            <%= f.label :password %>
            <% if @minimum_password_length %>
                <em>(<%= @minimum_password_length %> characters minimum)</em>
            <% end %><br />
            <%= f.password_field :password, autocomplete: 'off', class: 'form-control' %>
          </fieldset>
        </div>

        <div class="col-sm-6">
          <fieldset class="form-group">
            <%= f.label :password_confirmation %><br />
            <%= f.password_field :password_confirmation, autocomplete: 'off', class: 'form-control' %>
          </fieldset>
        </div>
      </div>

        <p>&nbsp;</p>

        <div class="actions">
          <%= f.submit 'Create User', class: 'btn btn-primary' %>
        </div>
    <% end %>

    <%= link_to 'Cancel', schools_path, class: 'chalk_link' %>

  </div>
</div>

app/views/schools/show.html.erb
<%= render 'layouts/header_main' %>

<div class="content_column content_overlay">
  <div class="container-fluid">

    <h1>Edit School Info</h1>

    <p id="notice"><%= notice %></p>

    <table class="table">
      <thead>
      <tr>
        <th>Name</th>
        <th>Address</th>
        <th>City</th>
        <th>State</th>
        <th>Zip</th>
        <th>Mascot</th>
      </tr>
      </thead>

      <tbody>
      <tr>
        <td><%= @school.name %></td>
        <td><%= @school.address %></td>
        <td><%= @school.city %></td>
        <td><%= @school.state %></td>
        <td><%= @school.zip %></td>
        <td><%= @school.mascot %></td>
      </tr>
      </tbody>
    </table>

    <%= link_to 'Edit School', edit_school_path(@school), class: "btn btn-primary" %>
    <p>&nbsp;</p>
    <%= link_to 'Back', schools_path, class: "btn btn-danger" %>
  </div>
</div>

app/views/schools/students.html.erb
<%= render 'layouts/header_main' %>

<div class="content_overlay content_column">
  <div class="container-fluid content_overlay">
    <p id="notice"><%= notice %></p>

    <h1>Students</h1>

      <table class="table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th colspan="2">Admin Options</th>
          </tr>
        </thead>

        <tbody>
        <% @students.each do |student| %>
          <tr>
            <td><%= student.first_name %> <%= student.last_name %></td>
            <td><%= student.email %></td>
            <td><%= link_to 'Edit', school_edit_user_path(student.id), class: 'btn btn-warning' %></td>
            <td><%= link_to 'Delete', school_delete_user_path(student.id), class: 'btn btn-danger', method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
        </tbody>
      </table>

    <p>&nbsp;</p>

    <div class="actions">
      <%= link_to 'New Student', school_new_user_path, class: 'btn btn-primary' %>
    </div>

    <%= link_to 'Cancel', schools_path, class: 'chalk_link' %>

  </div>
</div>

app/views/schools/teachers.html.erb
<%= render 'layouts/header_main' %>

<div class="content_overlay content_column">
  <div class="container-fluid content_overlay">
    <p id="notice"><%= notice %></p>

    <h1>Teachers</h1>

      <table class="table">
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th colspan="2">Admin Options</th>
          </tr>
        </thead>

        <tbody>
        <% @teachers.each do |teacher| %>
          <tr>
            <td><%= teacher.first_name %> <%= teacher.last_name %></td>
            <td><%= teacher.email %></td>
            <td><%= link_to 'Edit', school_edit_user_path(teacher.id), class: 'btn btn-warning' %></td>
            <td><%= link_to 'Delete', school_delete_user_path(teacher.id), class: 'btn btn-danger', data: { confirm: 'Are you sure?' }, method: :delete %></td>
          </tr>
        <% end %>
        </tbody>
      </table>

    <p>&nbsp;</p>

    <div class="actions">
      <%= link_to 'New Teacher', school_new_user_path, class: 'btn btn-primary' %>
    </div>

    <%= link_to 'Cancel', schools_path, class: 'chalk_link' %>

  </div>
</div>