config/routes.rb
Rails.application.routes.draw do

  root to: 'games#index'

  get 'games', to: 'games#index'
  get 'games/game_session', to: 'games#game_session'
  get 'games/game_session_questions/:id', to: 'games#game_session_questions'
  get 'games/collegiate_rivals', to: 'games#collegiate_rivals'

  get 'profiles', to: 'profiles#show'
  get 'profiles/:id', to: 'profiles#show'
  get 'profiles/:id/edit', to: 'profiles#edit'

  get 'schools/teachers', to: 'schools#teachers'
  get 'schools/students', to: 'schools#students'
  get 'schools/new_user', to: 'schools#new_user', as: 'school_new_user'
  get 'schools/edit_user/:id', to: 'schools#edit_user', as: 'school_edit_user'
  post 'schools/new_user', to: 'schools#create_new_user'
  patch 'schools/edit_user/:id', to: 'schools#update_user', as: 'school_update_user'
  delete 'schools/new_user/:id', to: 'schools#delete_user', as: 'school_delete_user'

  get 'questions/classroom/:id', to: 'questions#classroom', as: 'classroom_questions'
  get 'questions/classroom/:id/new', to: 'questions#new', as: 'new_classroom_question'
  post 'questions/classroom/:classroom_id', to: 'questions#create', as: 'create_new_classroom_question'

  get 'classroom_users/classroom/:id', to: 'classroom_users#index', as: 'classroom_users_class'
  post 'classroom_users/classroom/:id', to: 'classroom_users#create', as: 'classroom_users_add'

  post 'rewards/send_email', to: 'rewards#send_email'

  devise_for :users, controllers: {
      sessions: 'users/sessions'
  }
  resources :schools
  resources :classrooms
  resources :questions
  resources :classroom_users
end

app/views/layouts/_header_main.html.erb
<div class="chalkboard_background">
</div>

<div class="header_column">
  <header class="static_header content_overlay">
    <h2>The Chalkboard Classroom</h2>

    <ul>
    <% if user_signed_in? %>
      <% if @user.role > 0 %>
        <li><%= link_to "Classrooms", classrooms_path %></li>
      <% end %>

      <% if @user.role == 2 %>
        <li><%= link_to "School", schools_path %></li>
      <% end %>

      <li><%= link_to "Games", root_path %></li>
      <li><%= link_to "Profile", profiles_path %></li>
      <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
    <% else %>
      <li><%= link_to "Sign In", new_user_session_path, method: :get %></li>
    <% end %>
    </ul>
  </header>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Chalkboard Classroom | User Portal</title>

  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="white-translucent">
  <meta name="viewport" content="initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no, width=device-width, minimal-ui">

  <link href='https://fonts.googleapis.com/css?family=Oswald' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="body_wrapper">
  <div class="bg_color">
  </div>
</div>

<div class="content_wrapper">
  <%= yield %>
</div>

</body>
</html>